// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdkpmyznxfthobxpyryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka3BteXpueGZ0aG9ieHB5cnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNTQ3MDksImV4cCI6MjA4MDkzMDcwOX0.PXuYBjeyoVDWi_D2tP_I7HuLJ85-XzDNu0e0jDfjQUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});